FROM java:8-jdk-alpine

RUN apk add --update font-adobe-100dpi ttf-dejavu fontconfig mkfontscale

COPY font/simsun.ttc /usr/share/fonts/
COPY font/msyh.ttc /usr/share/fonts/
COPY font/msyhbd.ttc /usr/share/fonts/
COPY font/msyhl.ttc /usr/share/fonts/

RUN chmod 755 /usr/share/fonts/*
RUN mkfontscale
RUN mkfontdir
RUN fc-cache -fv
